"""
Generates heart-rate telemetry events during workouts.

This is the highest-volume domain: roughly one sample per minute of workout
duration, across every workout generated by workouts.py. Each sample derives
its time window and workout_id from an already-generated workout_completed
event, which is why heart_rate generation always runs after workouts.
"""

from datetime import datetime, timedelta

from src.generators.config import GeneratorConfig
from src.generators.common import make_envelope


def _parse_iso(ts: str) -> datetime:
    return datetime.strptime(ts, "%Y-%m-%dT%H:%M:%SZ")


def generate_heart_rate_events(
    workout_events: list[dict],
    config: GeneratorConfig,
    rng,
) -> list[dict]:
    starts: dict[str, dict] = {}
    completions: dict[str, dict] = {}
    for event in workout_events:
        if event["event_type"] == "workout_started":
            starts[event["workout_id"]] = event
        elif event["event_type"] == "workout_completed":
            completions[event["workout_id"]] = event

    events: list[dict] = []

    for workout_id, start_event in starts.items():
        completed_event = completions.get(workout_id)
        if completed_event is None:
            continue

        start_time = _parse_iso(start_event["event_timestamp"])
        end_time = _parse_iso(completed_event["event_timestamp"])
        span_minutes = max(1, int((end_time - start_time).total_seconds() // 60))

        user_id = start_event["user_id"]
        device_id = start_event["device_id"]
        schema_version = start_event["schema_version"]

        base_bpm = rng.randint(60, 80)
        peak_bpm = rng.randint(140, 180)

        samples_per_minute = config.heart_rate_samples_per_workout_minute
        num_samples = max(1, int(span_minutes * samples_per_minute))

        for i in range(num_samples):
            progress = i / max(1, num_samples - 1)
            ramped_bpm = base_bpm + (peak_bpm - base_bpm) * progress
            bpm = round(ramped_bpm + rng.uniform(-5, 5))

            sample_time = start_time + timedelta(minutes=i / samples_per_minute)

            events.append({
                **make_envelope("heart_rate_sample", sample_time, user_id, device_id, schema_version, rng),
                "workout_id": workout_id,
                "bpm": bpm,
            })

    return events